### ISSUE TITLE
Constraint for Teilnehmer Table

### ISSUE THREAD

**Issue by Menkir** [AndreasMReumschuessel/OneDayVR_Registration#1]
@AndreasMReumschuessel damit wir maximal N Teilnehmer haben.

**Comment by AndreasMReumschuessel** [comment]
Trigger ist erstellt in [max_teilnehmer_trigger.sql](https://github.com/AndreasMReumschuessel/OneDayVR_Registration/blob/master/sql_data/max_teilnehmer_trigger.sql).
Bin aber nicht so der Fan davon, dass weitere Teilnehmerdaten einfach verworfen werden.
