### ISSUE TITLE
Debug SQL Connection

### ISSUE THREAD

**Issue by lemistt** [AndreasMReumschuessel/OneDayVR_Registration#11]
Sometimes the SQL connection gets refused or time-outed and that crashes the server completely. Furthermore it seems the back-end connection to the server with it is not as secure as anticipated. 

Check server logs required @AndreasMReumschuessel

**Comment by AndreasMReumschuessel** [comment]
This is the [server log](https://github.com/AndreasMReumschuessel/OneDayVR_Registration/files/1659326/application.log).

**Comment by AndreasMReumschuessel** [comment]
Seems to work now.
