### ISSUE TITLE
Validation for form

### ISSUE THREAD

**Issue by Menkir** [AndreasMReumschuessel/OneDayVR_Registration#2]
@stefanleminh 
Die Entries sollten noch irgendwie validiert werden.

**Comment by lemistt** [comment]
@Dev7353 Back-End validation

**Comment by Menkir** [comment]
Es muss noch eine prüfung geben die eine maximale größe abprüft. Hab im backend einen fehler bekommen weil die plz zu lang ist, das könnte man schon im client abfangen.

**Comment by lemistt** [comment]
Gotcha - Was soll die maximale Größe sein?
