### ISSUE TITLE
Firmenname wird nicht angezeigt

### ISSUE THREAD

**Issue by AndreasMReumschuessel** [AndreasMReumschuessel/OneDayVR_Registration#5]
@Dev7353 
Es wird "firma" in der DB gespeichert statt ders Firmennamens. Wahrscheinlich wertest du nur "firmaOptions" aus.

**Comment by lemistt** [comment]
Back-End validation musst du auch nochmal drüberschauen, ob die regexes so passen - Leerzeichen in der Telefonnummer ging nicht und es werden keine Großbuchstaben in der E-Mail akzeptiert.
