### ISSUE TITLE
Front-End work

### ISSUE THREAD

**Issue by lemistt** [AndreasMReumschuessel/OneDayVR_Registration#6]
- [x] Need to recheck Front-End Validation, especially German formats for phone numbers etc.
- [x] Only mark the wrong labels, not the already corrected ones
- [x] Clear form upon success
- [x] Replace key visual and resize it properly

**Comment by AndreasMReumschuessel** [comment]
- [x] Change the title of the page.

**Comment by AndreasMReumschuessel** [comment]
- [x] Form should not be cleared when the backend sends an error.
- [x] Reset academic title and private field selector after successful submission.
