### ISSUE TITLE
No plus symbol in CSV export

### ISSUE THREAD

**Issue by AndreasMReumschuessel** [AndreasMReumschuessel/OneDayVR_Registration#7]
When exporting the whole participant table, the plus sympol isn't exported to the CSV.

**Comment by lemistt** [comment]
@AndreasMReumschuessel Is this resolved?

**Comment by AndreasMReumschuessel** [comment]
Yes! Excel imports the phone number as a calculation rather than a text, so this is why the plus isn't showing up when the csv isn't properly imported.
